### ISSUE TITLE
Add `Framework :: Hypothesis` PyPI trove classifier

### ISSUE THREAD

**Issue by Zac-HD** [tuturto/archimedes#7]
The Python Packaging Authority has recently created a new trove classifier to help users find Hypothesis-related packages, as described and demonstrated in HypothesisWorks/hypothesis#1663.

It would be great if this package used it too!

**Comment by tuturto** [comment]
This is great idea. I'll have to find my login credentials for PyPi and refresh my memory a bit (haven't been doing PyPi releases in a bit now), but I'll definitely look into this in the evening.

**Comment by tuturto** [comment]
Commit c15f0949a adds new trove classifier and new version has been uploaded to https://pypi.org/project/libarchimedes/0.4.2/
Thanks for the heads up @Zac-HD

**Comment by Zac-HD** [comment]
And you're officially the first project to release with the classifier!  Thanks for the awesome package and quick response :heart_eyes:
